# Generated by Django 4.2.29 on 2026-03-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_id_alter_detectionrule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='rule_type',
            field=models.CharField(choices=[('process', 'Process Name'), ('cpu', 'CPU Threshold'), ('network', 'Suspicious IP/Host')], max_length=20),
        ),
    ]
