# Generated by Django 5.2.12 on 2026-03-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_detectionrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_percent', models.FloatField(default=0)),
                ('cpu_percent', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='alerts.machine')),
            ],
        ),
    ]
